apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      serviceAccount: nfd-worker
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      hostNetwork: true
      serviceAccount: nfd-worker
      readOnlyRootFilesystem: true
      containers:
        - name: nfd-worker
          image: k8s.gcr.io/nfd/node-feature-discovery:v0.11.0
          imagePullPolicy: IfNotPresent
          command:
            - "nfd-worker"
          args:
            - "-server=nfd-master:8080"
          ports:
            - name: metrics
              containerPort: 8081
