apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-worker
spec:
  selector:
    matchLabels:
      app: nfd-worker
  template:
    metadata:
      labels:
        app: nfd-worker
    spec:
      serviceAccount: nfd-worker
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
      hostNetwork: true
      serviceAccount: nfd-worker
      readOnlyRootFilesystem: true
      containers:
        - name: nfd-worker
          image: k8s.gcr.io/nfd/node-feature-discovery:v0.11.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 10
          command:
            - "nfd-worker"
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 5m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 8080
